@startuml
' описание синтаксиса
' https://github.com/plantuml-stdlib/C4-PlantUML
' библиотеки C4
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

' доп.иконки для сервисов
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!include DEVICONS/java.puml
!include DEVICONS/msql_server.puml

AddElementTag("ВРаботе", $bgColor="#FFD700")
AddElementTag("Готово", $bgColor="#008000")
AddElementTag("НеПриступали", $bgColor="#F08080")

' раскомментировать, если файлы расположили локально (путь к файлам)
' !include C4_Container.puml

' текст без переноса
' skinparam wrapWidth 300 
' линии без скруглений
skinparam Linetype ortho
' skinparam Linetype polyline
' LAYOUT_LANDSCAPE()
' LAYOUT_TOP_DOWN()
' LAYOUT_AS_SKETCH()
' LAYOUT_WITH_LEGEND()

title
 <b>Торгово-производственная компания с маркетплейсами на ERP.УХ</b>
end title 

' наша большая система над которой мы работаем
System_Boundary(ЕРПУХ, "ERP Управление холдингом",) {
    Container(ТранспортнаяЛогистика, "Транспортная логистика", "Заявка, Сделка","",$tags="ВРаботе")
    Container(ВнешняяЛогистика, "Внешняя логистика", "Логистика за пределами РФ","",$tags="Готово")
    Container(ПродажиОпт, "Продажи Оптовые, проектные", "Заказ, сделка, ком.предложение, реализация","",$tags="НеПриступали")
    Container(ЭлектроннаяКоммерция, "Электронная коммерция", "Заказы, остатки, статусы","",$tags="ВРаботе")
    Container(Маркетинг, "Маркетинг", "Цены","",$tags="НеПриступали")
    Container(Казначейство, "Казначейство", "Заявки на платеж, реестр, платежи","",$tags="ВРаботе")
    Container(Закупки, "Закупки", "Заказы, импорт","",$tags="Готово")
    Container(Склад, "Склад", "Поступления на склад + ордера","",$tags="Готово")
    Container(НСИ, "НСИ", "Ведение и согласование НСИ","",$tags="Готово")
    Container(Производство, "Производство", "Заказы, выпуск, калькуляция, распределение затрат","",$tags="НеПриступали")    
    Container(Гарантия, "Гарантия и сервисное обслуживание", "Претензии, возвраты, замены, брак","",$tags="Готово")    
}

' В виде компонент
Component(ESB,"ESB-шина","Шина для работы маркетплейсами", $sprite="java",)

' системы которые наша команда тоже делает
System(ВМС, "WMS", "Складские операции","",$tags="ВРаботе")

' внешние системы
System_Ext(Бухгалтерия, "Бухгалтерия", "Регламентированный бухгалтерский учет")
System_Ext(ЗУП, "ЗУП", "Кадровый учет и зарплаты")

System_Ext(МаркетПлейсСвой, "Маркетплейс собственный", "Заказы, остатки, взаиморасчеты, доставка")


System_Ext(Озон,"OZON")
System_Ext(Вайлдберриз,"Вайлдберриз")
System_Ext(Яндекс,"Яндекс-маркет")



' Внутренние связи
Rel_L(ТранспортнаяЛогистика, ПродажиОпт,"")
Rel(ПродажиОпт, ВМС,"")
Rel(ПродажиОпт, Гарантия,"")
Rel(Закупки, ВнешняяЛогистика,"")
Rel(Закупки, Маркетинг,"")
Rel(Маркетинг, ПродажиОпт,"")
BiRel(Склад, Производство,"")
BiRel(Склад, ПродажиОпт,"")
BiRel(ПродажиОпт, Производство,"")
BiRel(Склад, Гарантия,"")

' Внешние связи
' первой связи Rel_U ставим вторую систему ВМС вверх
Rel_U(НСИ, ВМС,"")
BiRel(Склад, ВМС,"")

BiRel(ЭлектроннаяКоммерция, МаркетПлейсСвой,"web soap: Заказы,Остатки,Товары,Взаиморасчеты")

' Обмен в обе стороны
BiRel(ЭлектроннаяКоммерция, ESB,"https")
BiRel(ESB, Озон,"htpps")
BiRel(ESB, Вайлдберриз,"https")
BiRel(ESB, Яндекс,"https")

Rel_D(ЕРПУХ, Бухгалтерия,"Данные по продажам")
Rel_U(ЗУП, НСИ,"Физ.лица, структура предприятия, кадровая история")

' Расположение систем относительно друг друга (для выравнивания)
' Lay_U(ЕРПУХ,ВМС)
Lay_R(ESB, ЕРПУХ)
Lay_D(ТранспортнаяЛогистика, ПродажиОпт)
Lay_D(ВнешняяЛогистика, Закупки)
'Lay_D(Бухгалтерия, ЕРПУХ)


@enduml