@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' LAYOUT_WITH_LEGEND()

title Взаимодействие ERP, WMS и B2B в 1С

' Системы
System_Boundary(ERP, "1C:ERP") {
    Container(HtppServer, "Http-сервер", "Создание заказов поставщика")
}
System(WMS, "1С:WMS")

System_Ext(Шина, "Шина данных")
System_Ext(B2B, "Сервис B2B")  

' Связи
Rel_D(WMS, Шина, "Передача номенклатуры")
Rel_R(Шина, ERP, "Передача номенклатуры")
Rel(B2B, HtppServer, "Данные по заказам", "http")


@enduml
