@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

' LAYOUT_WITH_LEGEND()

title Архитектура 1С

Person(СпециалистЗУП, Бухгалтер по ЗП, "Специалист 1С:ЗУП")
Person(СотрудникКомпании, Сотрудники, "Сотрудник компании")

' Системы
System_Boundary(ЗУП, "1C:ЗУП") {
    Container(КадровыйУчет, "Кадровый учет", "")
    Container_Boundary(ЗП_Учет, "Учет зарплаты", ""){
        Component(ОтражениеЗП_ЗУП, "Отражение зарплаты в бухучете",, "")
    } 
}

System_Boundary(Бухгалтерия, "1C:Бухгалтерия") {
    Container(РеглУчетБП, "Регламентированный учет", "")
    Component(ОтражениеЗП_БП, "Отражение зарплаты в бухучете", , "")
}

System_Ext(ПочтоваяСистема, "E-mail сервер")  
System_Ext(ЛичныйКабинет, "1C Личный кабинет", "web_app")  

System_Boundary(ЕРП, "1С: ЕРП") {
    Container(УчетНСИ, "Учет НСИ", "Виды номенклатуры, Номенклатура, Контрагенты")
    Container(МобильноеПриложение, "Мобильное приложение")
}

System_Ext(ESB, "Шина ESB")


' Связи
Rel(СпециалистЗУП, ЗУП, "Ввод данных")
Rel(ОтражениеЗП_ЗУП, ОтражениеЗП_БП, "Данные по ЗП", "Типовой обмен 1С (КД 3)")
Rel(ЗУП, ПочтоваяСистема, "Расчетные листки сотрудникам", "ежемесячно")
Rel(ПочтоваяСистема, СотрудникКомпании, "Расчетные листки сотрудникам", "ежемесячно")

Rel_Back(ЗУП, ЛичныйКабинет, "Данные отпуска")
Rel(СотрудникКомпании, ЛичныйКабинет, "Оформление отпуска")

' Обмен ЕРП с БП
Rel(УчетНСИ, ESB, "Номенклатура", "https")
Rel(ESB, Бухгалтерия, "Номенклатура", "https")

' Расположение
Lay_U(ОтражениеЗП_ЗУП, ЗП_Учет)
Lay_U(СотрудникКомпании, ЛичныйКабинет)


@enduml
